name: "ONVIF PTZ Helper"
version: "2026.3.33"
slug: "onvif_ptz_helper"
description: "Helps some ONVIF cameras that don't update their PTZ movement to idle"
url: "https://github.com/jumpinf00l/dev_onvif_ptz_stabiliser/tree/main/onvif_ptz_helper"
license: MIT
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
boot: auto
backup: cold
options:
  log_level: "INFO"
  cameras: []
schema:
  log_level: list(DEBUG|INFO|WARNING|ERROR|CRITICAL)
  cameras:
    - camera_name: str
      host: str
      port: port
      ignore_ssl: bool?
      username: str
      password: password
      reconnect_time: float(0,)?
      idle_polling_interval: float(0,)?
      active_polling_interval: float(0,)?
      active_polling_history: int(2,)?
